services:
  accounts:
    image: "sondang2906/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - minibank
  loans:
    image: "sondang2906/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - minibank
  cards:
    image: "sondang2906/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - minibank
networks:
  minibank:
    driver: "bridge"