build:
  version: "1.0"

cards:
  message: "Welcome to MiniBank cards related local APIs"
  contactDetails:
    name: "Son Dang - Developer"
    email: "dangngocson29062003@gmail.com"
  onCallSupport:
    - 0793610514